
# fly.toml app configuration file for wine-ia-production
app = "wine-ia-production"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5001"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
