
app = "wine-ia-sommelier"
region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5001"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
